### PR TITLE
Support for Raspberry Pi 1

### PR DESCRIPTION
**Pull request by HorayNarea**

### CODE REVIEW

**Comment by rycus86** [comment]
Awesome, thanks @HorayNarea !
This still works on the RPi 2/3, right?
I'll try it on an RPi3 once built, don't have an RPi2 online at the moment though.

**Comment by rycus86** [comment]
Hm... The new version of Docker breaks non-interactive login on Travis, so I'll have to fix it later today.

**Comment by HorayNarea** [comment]
Yes it still works on RPi 2 and 3*, but it may be a tiny bit slower
…in the real world i have never noticed a real speed-difference between ARMv6 and ARMv7 Go Binaries

*in 32-bit mode

**Comment by rycus86** [comment]
Great, thanks again!

**Pull request merged**
